export const FETCH_USER = 'FETCH_USER';
export const CREATE_RECIPIENT = 'CREATE_RECIPIENT';
export const FETCH_RECIPIENTS = 'FETCH_RECIPIENTS';
export const SAVE_BROADCAST = 'SAVE_BROADCAST';
export const FETCH_BROADCASTS = 'FETCH_BROADCASTS';