//Users
export const FETCH_USER = 'FETCH_USER';

//Recipients
export const SAVE_RECIPIENT = 'SAVE_RECIPIENT';
export const UPDATE_RECIPIENT = 'UPDATE_RECIPIENT';
export const FETCH_RECIPIENTS = 'FETCH_RECIPIENTS';
export const SET_RECIPIENT = 'SET_RECIPIENT';
export const UNSET_RECIPIENT = 'UNSET_RECIPIENT';

//Broadcasts
export const SAVE_BROADCAST = 'SAVE_BROADCAST';
export const FETCH_BROADCASTS = 'FETCH_BROADCASTS';

//Lists
export const SAVE_LIST = 'SAVE_LIST';
export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_LIST = 'FETCH_LIST';
export const SET_LIST = 'SET_LIST';
export const UNSET_LIST = 'UNSET_LIST';
export const FILTER_LISTS = 'FILTER_LISTS';
export const FILTER_RECIPIENTS = 'FILTER_RECIPIENTS';
export const ADD_RECIPIENT_TO_LIST = 'ADD_RECIPIENT_TO_LIST';
export const REMOVE_RECIPIENT_FROM_LIST = 'REMOVE_RECIPIENT_FROM_LIST';
export const ADD_LIST_TO_BROADCAST = 'ADD_LIST_TO_BROADCAST';
export const REMOVE_LIST_FROM_BROADCAST = 'REMOVE_LIST_FROM_BROADCAST';
export const UNSET_BROADCAST_LISTS = 'UNSET_BROADCAST_LISTS';
