//Users
export const FETCH_USER = 'FETCH_USER';

//Recipients
export const SAVE_RECIPIENT = 'CREATE_RECIPIENT';
export const FETCH_RECIPIENTS = 'FETCH_RECIPIENTS';

//Broadcasts
export const SAVE_BROADCAST = 'SAVE_BROADCAST';
export const FETCH_BROADCASTS = 'FETCH_BROADCASTS';

//Lists
export const SAVE_LIST = 'SAVE_LIST';
export const FETCH_LISTS = 'FETCH_LISTS';
export const FETCH_LIST = 'FETCH_LIST';
export const SET_LIST = 'SET_LIST';
export const UNSET_LIST = 'UNSET_LIST';
export const FILTER_RECIPIENTS = 'FILTER_RECIPIENTS';
export const ADD_RECIPIENT_TO_LIST = 'ADD_RECIPIENT_TO_LIST';
export const REMOVE_RECIPIENT_FROM_LIST = 'REMOVE_RECIPIENT_FROM_LIST';